server:
  port: 7001

fdfs:
  so-timeout: 1500
  connect-timeout: 6000
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.158.128:22122

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    host: 192.168.158.128
    port: 5672
    username: kebi
    password: 123456
    virtual-host: /kebi
image:
  server:
    path: http://192.168.158.128/