spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.158.128
    port: 5672
    username: kebi
    password: 123456
    virtual-host: /kebi
  data:
    solr:
      host: http://192.168.158.128:8088/solr/
server:
  port: 8003